version: '3'

services:
  db:
    image: postgres:15
    container_name: ohagi
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ohagi
volumes:
  db-store:
